name: Run test Script on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v5

      - name: Create pages from multilingual yaml files
        run: ./scripts/build-pages.sh

      - name: Run build site script
        run: ./scripts/build-site-folder.sh

      - name: Run broken links
        run: ./scripts/broken-links.sh
